// HeroShader.tsx
// WebGL shader — dark navy with volumetric light, mouse-reactive.
// Generated by Claude Design, adapted for React/TypeScript.
// Usage: <HeroShader className="absolute inset-0" />

import { useEffect, useRef } from "react";

const VERT = `
attribute vec2 a_position;
void main() {
  gl_Position = vec4(a_position, 0.0, 1.0);
}
`;

const FRAG = `
precision highp float;

uniform vec2  u_resolution;
uniform float u_time;
uniform vec2  u_mouse;
uniform float u_pixelRatio;
uniform float u_intensity;
uniform float u_gold;
uniform float u_mouseAmt;

vec3 mod289(vec3 x){ return x - floor(x * (1.0/289.0)) * 289.0; }
vec2 mod289(vec2 x){ return x - floor(x * (1.0/289.0)) * 289.0; }
vec3 permute(vec3 x){ return mod289(((x*34.0)+1.0)*x); }

float snoise(vec2 v){
  const vec4 C = vec4(0.211324865405187, 0.366025403784439,
                     -0.577350269189626, 0.024390243902439);
  vec2 i  = floor(v + dot(v, C.yy));
  vec2 x0 = v -   i + dot(i, C.xx);
  vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);
  vec4 x12 = x0.xyxy + C.xxzz;
  x12.xy -= i1;
  i = mod289(i);
  vec3 p = permute( permute( i.y + vec3(0.0, i1.y, 1.0 ))
                  + i.x + vec3(0.0, i1.x, 1.0 ));
  vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);
  m = m*m; m = m*m;
  vec3 x  = 2.0 * fract(p * C.www) - 1.0;
  vec3 h  = abs(x) - 0.5;
  vec3 ox = floor(x + 0.5);
  vec3 a0 = x - ox;
  m *= 1.79284291400159 - 0.85373472095314 * (a0*a0 + h*h);
  vec3 g;
  g.x  = a0.x  * x0.x  + h.x  * x0.y;
  g.yz = a0.yz * x12.xz + h.yz * x12.yw;
  return 130.0 * dot(m, g);
}

float fbm(vec2 p){
  float v = 0.0;
  float a = 0.5;
  for (int i = 0; i < 5; i++){
    v += a * snoise(p);
    p  = p * 2.03 + vec2(1.7, 9.2);
    a *= 0.5;
  }
  return v;
}

float warped(vec2 p, float t){
  vec2 q = vec2(
    fbm(p + vec2(0.0, 0.0) + t*0.04),
    fbm(p + vec2(5.2, 1.3) - t*0.03)
  );
  vec2 r = vec2(
    fbm(p + 1.6*q + vec2(1.7, 9.2) + t*0.05),
    fbm(p + 1.6*q + vec2(8.3, 2.8) - t*0.04)
  );
  return fbm(p + 1.6*r);
}

float lightWell(vec2 uv, vec2 center, float radius, float falloff){
  float d = distance(uv, center);
  return pow(smoothstep(radius, 0.0, d), falloff);
}

void main(){
  vec2 frag = gl_FragCoord.xy / u_resolution.xy;
  float aspect = u_resolution.x / u_resolution.y;
  vec2 uv = frag;
  vec2 cuv = (uv - 0.5);
  cuv.x *= aspect;

  float t = u_time * 0.08;

  vec2 m = u_mouse - 0.5;
  m.x *= aspect;
  vec2 mOffset = m * 0.08 * u_mouseAmt;

  vec3 base = vec3(0.0235, 0.0314, 0.0588);

  vec2 p = cuv * 1.35;
  float w = warped(p + mOffset*2.0, u_time);
  float vol = smoothstep(-0.9, 1.1, w);

  float w2 = warped(p*0.55 + vec2(3.1, -1.7) + mOffset, u_time*0.6);
  float vol2 = smoothstep(-1.0, 1.0, w2);

  vec3 silver = vec3(0.70, 0.78, 0.90);
  vec3 deepBlue = vec3(0.08, 0.16, 0.34);
  vec3 midBlue  = vec3(0.04, 0.09, 0.22);

  vec2 L1 = vec2(-0.55 + 0.08*sin(t*0.9),  0.18 + 0.06*cos(t*0.7)) + mOffset;
  vec2 L2 = vec2( 0.45 + 0.10*cos(t*0.6), -0.22 + 0.08*sin(t*0.8)) + mOffset*0.6;
  vec2 L3 = vec2( 0.05 + 0.12*sin(t*0.5 + 1.4), 0.35 + 0.05*cos(t*0.4)) + mOffset*0.4;

  float l1 = lightWell(cuv, L1, 0.95, 1.6);
  float l2 = lightWell(cuv, L2, 1.10, 1.8);
  float l3 = lightWell(cuv, L3, 0.70, 2.2);

  float lightMass = (l1*0.55 + l2*0.50) * mix(0.35, 1.0, vol);
  float rim       = l3 * mix(0.25, 1.0, vol2);

  vec3 gold = vec3(0.82, 0.66, 0.35);
  float goldBand = smoothstep(0.55, 0.85, vol2) * smoothstep(0.35, 0.9, l2);
  float goldFactor = goldBand * 0.12 * u_gold;

  vec3 col = base;
  col = mix(col, midBlue, vol * 0.55);
  col = mix(col, deepBlue, vol2 * 0.35);
  col += silver * lightMass * 0.28 * u_intensity;
  col += silver * rim * 0.10 * u_intensity;
  col = mix(col, gold, goldFactor);

  float sheen = dot(normalize(cuv - mOffset*3.0 + vec2(0.001)), vec2(0.6, 0.8));
  sheen = smoothstep(-0.2, 1.0, sheen);
  col += vec3(0.04, 0.06, 0.09) * sheen * 0.6;

  float vig = smoothstep(1.35, 0.35, length(cuv));
  col *= mix(0.55, 1.0, vig);

  float grain = fract(sin(dot(gl_FragCoord.xy + u_time*60.0, vec2(12.9898, 78.233))) * 43758.5453);
  col += (grain - 0.5) * 0.012;

  col = max(col, vec3(0.0235, 0.0314, 0.0588));

  gl_FragColor = vec4(col, 1.0);
}
`;

function compile(gl: WebGLRenderingContext, type: number, src: string): WebGLShader | null {
  const s = gl.createShader(type);
  if (!s) return null;
  gl.shaderSource(s, src);
  gl.compileShader(s);
  if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) {
    console.error("Shader compile error:", gl.getShaderInfoLog(s));
    gl.deleteShader(s);
    return null;
  }
  return s;
}

interface HeroShaderProps {
  className?: string;
  style?: React.CSSProperties;
}

export function HeroShader({ className, style }: HeroShaderProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const gl = (
      canvas.getContext("webgl", { antialias: false, alpha: false, premultipliedAlpha: false }) ||
      canvas.getContext("experimental-webgl")
    ) as WebGLRenderingContext | null;

    if (!gl) {
      canvas.style.background = "#06080f";
      return;
    }

    const vs = compile(gl, gl.VERTEX_SHADER, VERT);
    const fs = compile(gl, gl.FRAGMENT_SHADER, FRAG);
    if (!vs || !fs) return;

    const prog = gl.createProgram()!;
    gl.attachShader(prog, vs);
    gl.attachShader(prog, fs);
    gl.linkProgram(prog);
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) {
      console.error("Program link error:", gl.getProgramInfoLog(prog));
      return;
    }
    gl.useProgram(prog);

    const buf = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    const posLoc = gl.getAttribLocation(prog, "a_position");
    gl.enableVertexAttribArray(posLoc);
    gl.vertexAttribPointer(posLoc, 2, gl.FLOAT, false, 0, 0);

    const uRes      = gl.getUniformLocation(prog, "u_resolution");
    const uTime     = gl.getUniformLocation(prog, "u_time");
    const uMouse    = gl.getUniformLocation(prog, "u_mouse");
    const uDPR      = gl.getUniformLocation(prog, "u_pixelRatio");
    const uIntensity= gl.getUniformLocation(prog, "u_intensity");
    const uGold     = gl.getUniformLocation(prog, "u_gold");
    const uMouseAmt = gl.getUniformLocation(prog, "u_mouseAmt");

    const mouse = { tx: 0.5, ty: 0.5, x: 0.5, y: 0.5 };
    const onMove = (e: MouseEvent) => {
      const rect = canvas.getBoundingClientRect();
      mouse.tx = (e.clientX - rect.left) / rect.width;
      mouse.ty = 1.0 - (e.clientY - rect.top) / rect.height;
    };
    const onLeave = () => { mouse.tx = 0.5; mouse.ty = 0.5; };
    const onTouch = (e: TouchEvent) => {
      if (!e.touches?.[0]) return;
      const rect = canvas.getBoundingClientRect();
      mouse.tx = (e.touches[0].clientX - rect.left) / rect.width;
      mouse.ty = 1.0 - (e.touches[0].clientY - rect.top) / rect.height;
    };

    window.addEventListener("mousemove", onMove, { passive: true });
    window.addEventListener("mouseleave", onLeave, { passive: true });
    window.addEventListener("touchmove", onTouch, { passive: true });

    const resize = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 1.75);
      const w = canvas.clientWidth;
      const h = canvas.clientHeight;
      const pw = Math.max(1, Math.floor(w * dpr));
      const ph = Math.max(1, Math.floor(h * dpr));
      if (canvas.width !== pw || canvas.height !== ph) {
        canvas.width = pw;
        canvas.height = ph;
      }
      gl.viewport(0, 0, canvas.width, canvas.height);
      gl.uniform1f(uDPR, dpr);
    };
    const ro = new ResizeObserver(resize);
    ro.observe(canvas);
    resize();

    let visible = true;
    const io = new IntersectionObserver(([e]) => { visible = e.isIntersecting; }, { threshold: 0 });
    io.observe(canvas);

    let pageVisible = !document.hidden;
    let last = performance.now();
    const onVis = () => { pageVisible = !document.hidden; last = performance.now(); };
    document.addEventListener("visibilitychange", onVis);

    const start = performance.now();
    let rafId = 0;

    const render = (now: number) => {
      rafId = requestAnimationFrame(render);
      if (!visible || !pageVisible) return;

      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;

      const k = 1 - Math.pow(0.001, dt);
      mouse.x += (mouse.tx - mouse.x) * k;
      mouse.y += (mouse.ty - mouse.y) * k;

      gl.uniform2f(uRes, canvas.width, canvas.height);
      gl.uniform1f(uTime, (now - start) / 1000);
      gl.uniform2f(uMouse, mouse.x, mouse.y);
      gl.uniform1f(uIntensity, 1.0);   // standard
      gl.uniform1f(uGold, 1.0);        // subtle gold
      gl.uniform1f(uMouseAmt, 1.0);    // 8% mouse influence

      gl.drawArrays(gl.TRIANGLES, 0, 3);
    };
    rafId = requestAnimationFrame(render);

    return () => {
      cancelAnimationFrame(rafId);
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("mouseleave", onLeave);
      window.removeEventListener("touchmove", onTouch);
      document.removeEventListener("visibilitychange", onVis);
      ro.disconnect();
      io.disconnect();
      gl.deleteBuffer(buf);
      gl.deleteShader(vs);
      gl.deleteShader(fs);
      gl.deleteProgram(prog);
      const loseExt = gl.getExtension("WEBGL_lose_context");
      if (loseExt) loseExt.loseContext();
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className={className}
      style={{ display: "block", width: "100%", height: "100%", background: "#06080f", ...style }}
    />
  );
}
